# Generated by Django 5.0 on 2023-12-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
